[AUTH]
usernames = admin4,modelowner4,modeluser4,modelviewer4
passwords = 123456,asdf1234,asdf1234,asdf1234
keycloak_url = https://passport.geobeans.cn
realm_name = onesis
client_id = onesis-geomodel
client_secret_key = MnDCSHvuZkn7wrDrmbyjm9oUpiYdYNdz

[SERVICE]
modelmanager_url = http://localhost:7504
api_basename = mbms/v1
# APIs of model management
api_cls_modelmanager = model-manager
# modelmanager_url/api_basename/api_cls_modelmanager/api_mgt_generalmodel/
api_mgt_generalmodel = general-models
api_gm_catalog = catalog
api_gm_catalogcls = catalog/categories
api_gm_catalogappl = catalog-application

# API version control
# Specify v2 for APIs that have been upgraded, unspecified ones use default version from api_basename
# Catalog series APIs use v2
api_version_gm_catalog = v2
# UI-info API uses v2
api_version_sm_ui = v2

# modelmanager_url/api_basename/api_cls_modelmanager/api_mgt_generalmodel/
api_mgt_singlemodel = general-single-models
api_sm_list = list
# modelmanager_url/api_basename/api_cls_modelmanager/api_mgt_generalmodel/{id}/
api_sm_info = info
api_sm_ui = ui-info

# APIs of model runner
api_cls_runner = model-runner
# modelmanager_url/api_basename/api_cls_runner/api_run_singlemodel/{id}/
api_run_singlemodel = single-models
api_srun_run = run
# modelmanager_url/api_basename/api_cls_runner/api_run_singlemodel/api_srun_task/{taskId}/
api_srun_task = tasks
api_srunt_stop = stop
api_srunt_del = delete
api_srunt_info = run-info
api_srunt_log = run-log

# APIs of user project
api_cls_usrprj = user-projects
# modelmanager_url/api_basename/api_cls_usrprj/api_uprj_list
api_uprj_list = list
# modelmanager_url/api_basename/api_cls_usrprj/{id}/
api_uprj_data = data-info
api_uprj_log = log
api_uprj_detail = model-details
api_uprj_prog = progress
api_uprj_stop = stop
api_uprj_del = delete
# modelmanager_url/api_basename/api_cls_usrprj/api_uprj_single/{id}/
api_uprj_single = single-models
api_sprj_run = run

[FEATURE_FLAGS]
# 地形分析工具集开关
enable_terrain_analysis_tools = false
# EGC模型管理工具集开关
enable_model_management_tools = true
